#+TITLE: Chapter 1 Notes

* Terms
+ Financial Accounting :: Branch of accounting focused on the business
  information needs of external users (creditors, investors,
  governmental agencies, financial analysts, etc.); its objective is
  to classify and record business events and transactions to produce
  external financial reports (income statement, balance sheet,
  statement of cash flows, and statement of changes in equity).

+ Managerial Accounting :: Branch of accounting focused on the
  information needs of managers and others working within the
  business. Its objective is to gather and report information that
  adds value to the business. Managerial accounting information is not
  regulated or reported to the public.

+ Overhead :: Costs associated with producing products or providing
  services that cannot be traced directly to those products or
  services in a cost-effective manner; includes indirect costs such as
  indirect materials; indirect labor; utilities; rent; depreciation on
  manufacturing facilities and equipment; and planning, design, and
  setup costs related to the product or service.

+ Value Chain Analysis            :: Involves analyzing a company’s activities to identify areas of value creation and improve competitive advantage.
+ Total Quality Management (TQM)  :: Aims at continuous improvement in all operations to enhance quality and customer satisfaction.
+ Activity-Based Management (ABM) :: Focuses on managing activities as the basis for improving customer value and profit.
+ Lean Accounting                 :: Seeks to minimize waste and maximize value for the customer, often leading to cost reduction and efficiency improvement.
+ Throughput Accounting           :: Concentrates on maximizing the rate at which a system generates money through sales.
+ Sustainability Accounting       :: Focuses on incorporating environmental and social costs into decision-making processes.
+ Risk Management                 :: Involves identifying, assessing, and managing risks to minimize their impact on the organization.

* Check Yourself 1.1
Goods are priced based on the average cost per unit

* Check Yourself 1.2 (Cost-plus Pricing)
|---+------------------------+--------|
|   | Production Wages       | 100000 |
|   | Materials              | 120000 |
|   | Manufacturing Overhead | 160000 |
|   | Sales/Admin Salaries   |  80000 |
|   | Units Produced         |   1000 |
|   | Units Sold             |    800 |
|   | Per Unit Mark-Up       |    220 |
|---+------------------------+--------|

** Product Cost
|---+------------------+--------|
|   | Expense          |   Cost |
|---+------------------+--------|
|   | Production Wages | 100000 |
|   | Materials        | 120000 |
|   | Overhead         | 160000 |
|---+------------------+--------|
| # | Total            | 380000 |
|---+------------------+--------|

#+TBLFM: @5$3=vsum(@2$3..@-1$3)
** Cost per Unit
|---+-----------------+--------|
|   | Production Cost | 380000 |
|   | Units Produced  |   1000 |
|---+-----------------+--------|
| # | Cost per Unit   |    380 |
|---+-----------------+--------|
#+TBLFM: @3$3=(@1$3/@2$3)

|---+------------------+-----|
|   | Cost per Unit    | 380 |
|   | Mark-up per Unit | 220 |
|---+------------------+-----|
| # | Price per Unit   | 600 |
|---+------------------+-----|
#+TBLFM: @3$3=(@1$3+@2$3)

** Goods Sold
|---+---------------+--------|
|   | Cost per Unit |    380 |
|   | Units sold    |    800 |
|---+---------------+--------|
| # | Total Cost    | 304000 |
|---+---------------+--------|
#+TBLFM: @3$3=(@1$3*@2$3)

|---+----------------+--------|
|   | Price per Unit |    600 |
|   | Units sold     |    800 |
|---+----------------+--------|
| # | Sales revenue  | 480000 |
|---+----------------+--------|
#+TBLFM: @3$3=(@1$3*@2$3)

** Revenue
|---+---------------------+---------|
|   | Revenue             |  480000 |
|   | Costs of goods sold | -304000 |
|---+---------------------+---------|
| # | Gross Margin        |  176000 |
|---+---------------------+---------|
#+TBLFM: @3$3=(@1$3+@2$3)

|---+----------------------+--------|
|   | Gross Margin         | 178000 |
|   | Sales/Admin Salaries | -80000 |
|---+----------------------+--------|
| # | Net Income           |  98000 |
|---+----------------------+--------|
#+TBLFM: @3$3=(@1$3+@2$3)

* Check Yourself 1.3 (Five Guys)
The finished product (food) is consumed immediately.  This is the hallmark of a service company.
* Check Yourself 1.4
|---+-------------------------------------------+--------|
|   | Research and Development Cost             | -60000 |
|   | Fashion Design Cost                       | -40000 |
|---+-------------------------------------------+--------|
|   | Direct Materials (per-unit)               |    -30 |
|   | Direct Labor (per-unit)                   |    -35 |
|   | Maufactoring overhead (per-unit)          |    -15 |
|---+-------------------------------------------+--------|
|   | Production/Sales volume                   |   4000 |
|---+-------------------------------------------+--------|
|   | Advertising Cost                          | -50000 |
|   | Admin Cost                                | -90000 |
|---+-------------------------------------------+--------|
|   | Product Mark-Up (160% GAAP per unit cost) |    1.6 |
|---+-------------------------------------------+--------|

** Upstream Costs
|---+-------------------------------+--------|
|   | Research and Development Cost |  -60000 |
|   | Fashion Design Cost           |  -40000 |
|---+-------------------------------+--------|
| # | Total                         | 100000 |
|---+-------------------------------+--------|
#+TBLFM: @3$3=vsum(@1..@-1)

** Downstream Costs
|---+------------------+--------|
|   | Advertising Cost |  -50000 |
|   | Admin Cost       |  -90000 |
|---+------------------+--------|
| # | Total            | 140000 |
|---+------------------+--------|
#+TBLFM: @3$3=vsum(@1..@-1)

** Midstream Costs
|---+----------------------------------+---------|
|   | Direct Materials (per-unit)      |     -30 |
|   | Direct Labor (per-unit)          |     -35 |
|   | Maufactoring overhead (per-unit) |     -15 |
|---+----------------------------------+---------|
| # | Total per unit cost              |     -80 |
|---+----------------------------------+---------|
|   | Production/Sales volume          |    4000 |
|---+----------------------------------+---------|
| # | Total                            | -320000 |
|---+----------------------------------+---------|
#+TBLFM: @4$3=vsum(@1..@3)::@6$3=@-2*@-1

** Sales Price per Unit
|---+----------------------------------+--------|
|   | Direct Materials (per-unit)      |    -30 |
|   | Direct Labor (per-unit)          |    -35 |
|   | Maufactoring overhead (per-unit) |    -15 |
|---+----------------------------------+--------|
| # | Total per unit cost              |    -80 |
|   | Mark-up percent (via GAAP)       |    1.6 |
|---+----------------------------------+--------|
| # | Sales Price per Unit             | 128.00 |
|---+----------------------------------+--------|
#+TBLFM: @4$3=vsum(@1..@3)::@6$3=@-2*@-1*-1;%0.2f

** Income Statement (GAAP)
|---+----------------+--------|
|   | Price per Unit |    128 |
|   | Units Sold     |   4000 |
|---+----------------+--------|
| # | Sales Revenue  | 512000 |
|---+----------------+--------|
#+TBLFM: @3$3=@-2*@-1

|---+-------------------------+---------|
|   | Total per unit cost     |     -80 |
|   | Production/Sales volume |    4000 |
|---+-------------------------+---------|
| # | Cost of goods sold      | -320000 |
|---+-------------------------+---------|
#+TBLFM: @3$3=@-2*@-1

|---+------------------------------------------+---------|
|   | Upstream costs (R&D and design)          | -100000 |
|   | Downstream costs (admin and advertising) | -140000 |
|---+------------------------------------------+---------|
| # | Selling, Admin, General Costs            | -240000 |
|---+------------------------------------------+---------|
#+TBLFM: @3$3=@-1+@-2

|---+-------------------------------+---------|
|   | Sales Revenue                 |  512000 |
|   | Costs of goods sold           | -320000 |
|---+-------------------------------+---------|
| # | Gross margin                  |  192000 |
|---+-------------------------------+---------|
|   | Selling, Admin, General Costs | -240000 |
|---+-------------------------------+---------|
| # | Net                           |  -48000 |
|---+-------------------------------+---------|
#+TBLFM: @3$3=@-2+@-1::@5$3=@-2+@-1

** Explanation
Warm Zero Inc failed to account for upstream and downstream costs.

* Check Yourself 1.5 (General Motor Brake Plant Strike)

The strike effectively disabled all assembly plants as they lacked the inventory they needed from a JIT system.

* Study Guide

Chapter 1 provides an overview of key terms and concepts that help set the foundation of managerial accounting concepts.

1) Managerial accounting users have different information needs than
   financial accounting users (see LO 1-1).

   + Managerial accounting
     1. Focuses on the needs of internal users (i.e., company managers).
     2. Uses economic, operating, and nonfinancial, as well as financial, data.
     3. Local (pertains to the company’s subunits).
     4. Limited by cost/benefit considerations.
     5. More concerned with relevance and timeliness, and is future oriented.

   + Financial accounting
     1. Focuses on the information needs of external users (i.e., external investors).
     2. More global than managerial accounting information. Information that applies to the whole company.
     3. Regulated by numerous authorities.
     4. Characterized by objectivity.
     5. Focuses on reliability and accuracy, and is historical in nature.

2) Both managerial and financial accounting are concerned with
   differentiating product cost from period cost.

   + Product costs are the costs incurred to make products and are
     composed of three different types of costs: direct materials,
     direct labor, and overhead (see LO 1-2).

     1. Both direct materials and direct labor are labeled direct cost
        because these types of product costs can be easily traced to
        the product in a cost-efficient manner.

     2. Overhead is often referred to as an indirect cost because
        these types of product costs are not easily traced to the
        product in a cost-efficient manner. Overhead costs include
        indirect materials, indirect labor, depreciation, rent, and
        utilities for manufacturing facilities. Overhead or indirect
        costs must be assigned to the cost of a product through a
        process called cost allocation.

   + Period costs comprise all the other costs incurred to operate the
     business unrelated to making products, also commonly referred to
     as selling, general, and administrative costs (see LO 1-2).

   + The accounting treatment of product costs and period costs
     differs (see LO 1-3).

     1. In a manufacturing company, as product costs are incurred,
        they are first accumulated into the Inventory account on the
        balance sheet. Product costs will remain in the Inventory
        account until the product is sold. At this time, product costs
        will be expensed on the income statement as cost of goods
        sold. This can cause product costs to be incurred in one
        accounting period, but expensed in a different accounting
        period. Any product costs remaining in the Inventory account
        at the end of the period are referred to as ending inventory.

     2. Service companies, like manufacturing companies, incur
        materials, labor, and overhead costs, but the products
        provided by service companies are consumed
        immediately. Therefore, service company product costs are not
        accumulated in an Inventory account, as they are immediately
        expensed on the income statement.
     3. In contrast, period costs are never accumulated on the balance
        sheet, but rather immediately expensed on the income statement
        in the period they are incurred. These costs are shown as
        selling, general, and administrative costs on the income
        statement.

   + Financial accountants need product cost information to determine
     the amount of inventory reported on the balance sheet and the
     amount of cost of goods sold reported on the income
     statement. Managerial accountants need to know the cost of
     products for pricing decisions and for control and evaluation
     purposes. When determining unit product costs, managers use the
     average cost per unit (see LO 1-2). Determining the actual cost
     of each product requires an unreasonable amount of time and
     recordkeeping and it makes no difference in product pricing and
     product cost control decisions.

3) All costs incurred to operate a business can be subdivided into
   three categories (see LO 1-4):

   + Upstream costs are costs that are incurred prior to the
     manufacturing process, including research and development costs
     and product design costs.

   + Midstream costs are costs incurred in the process of making
     products, including direct materials, direct labor, and
     manufacturing overhead.

   + Downstream costs are incurred after the manufacturing process,
     including marketing, distribution, and customer services.

4) In order for a company to be profitable, it must ensure that it has
   enough inventory on hand to provide to its customers. However,
   having too much inventory on hand can result in incurring
   unnecessary expenditures, such as excess inventory and inventory
   storage costs. A common method of avoiding these excess expenses is
   to utilize a just-in-time (JIT) inventory system (see LO 1-5). The
   goal of a JIT inventory system is to reduce the amount of inventory
   on hand by ordering inventory as the customer requests it. The
   downside of JIT inventory systems is that the delay between
   receiving inventory and delivering it to the customer can result in
   lost sales.

5) Understand the core concepts of the value chain, namely its role in
   creating products that meet customer needs. This is accomplished by
   mapping out the sequence of value-adding activities within an
   organization. Strategic cost management (SCM) describes the various
   strategies that companies employ across the value chain to control
   costs and enhance performance, aligning these strategies with the
   organization’s long-term goals and operational challenges. The
   success or failure of a strategy is often determined through a
   process called benchmarking (see LO 1-6).

6) A code of ethical conduct is needed in the accounting profession
   because accountants hold positions of trust and face conflicts of
   interest. In recognition of the temptations that accountants face,
   the IMA has issued the Statement of Ethical Professional Practice,
   which provides accountants guidance in resisting temptations and in
   making difficult decisions (see LO 1-7).

7) The Appendix discusses modern trends in managerial
   accounting. Current topics covered in this edition include
   artificial intelligence, cloud computing, data analytics, and many
   more. Many technological advancements are having a profound impact
   on industry and having a foundational understanding of these topics
   is important for all business majors (see LO 1-8).

* Self-Study Review Problem

Tuscan Manufacturing Company makes a unique headset for use with
mobile phones. During Year 1, Tuscan experienced the following
accounting events. Other than the adjusting entries for depreciation,
assume that all transactions are cash transactions.
